/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FeatureHighlight = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ServerInfo = IDL.Record({
  'tagline' : IDL.Text,
  'memberCount' : IDL.Nat,
  'inviteURL' : IDL.Text,
  'description' : IDL.Text,
  'serverName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getFeatureHighlights' : IDL.Func([], [IDL.Vec(FeatureHighlight)], ['query']),
  'getRules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getServerInfo' : IDL.Func([IDL.Principal], [ServerInfo], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'updateFeatureHighlights' : IDL.Func([IDL.Vec(FeatureHighlight)], [], []),
  'updateRules' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateServerInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FeatureHighlight = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServerInfo = IDL.Record({
    'tagline' : IDL.Text,
    'memberCount' : IDL.Nat,
    'inviteURL' : IDL.Text,
    'description' : IDL.Text,
    'serverName' : IDL.Text,
  });
  
  return IDL.Service({
    'getFeatureHighlights' : IDL.Func(
        [],
        [IDL.Vec(FeatureHighlight)],
        ['query'],
      ),
    'getRules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getServerInfo' : IDL.Func([IDL.Principal], [ServerInfo], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'updateFeatureHighlights' : IDL.Func([IDL.Vec(FeatureHighlight)], [], []),
    'updateRules' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateServerInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };