/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeatureHighlight { 'title' : string, 'description' : string }
export interface ServerInfo {
  'tagline' : string,
  'memberCount' : bigint,
  'inviteURL' : string,
  'description' : string,
  'serverName' : string,
}
export interface _SERVICE {
  'getFeatureHighlights' : ActorMethod<[], Array<FeatureHighlight>>,
  'getRules' : ActorMethod<[], Array<string>>,
  'getServerInfo' : ActorMethod<[Principal], ServerInfo>,
  'isAdmin' : ActorMethod<[], boolean>,
  'updateFeatureHighlights' : ActorMethod<[Array<FeatureHighlight>], undefined>,
  'updateRules' : ActorMethod<[Array<string>], undefined>,
  'updateServerInfo' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];